AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    muphone 

    Cloudformation Template for the muphone microservice
    
Globals:
    Function:
        Timeout: 3

Resources:

    NewPhoneNumber:
        Type: AWS::Serverless::Function 
        Properties:
            CodeUri: hello_world/build/
            Handler: app.new_phone_number
            Runtime: python3.6
            Environment: 
                Variables:
                    SMS_PROVIER_KEY: VALUE
            Events:
                NewNumber:
                    Type: Api 
                    Properties:
                        Path: /phone
                        Method: post

Outputs:

    MuPhoneApi:
      Description: "API Gateway endpoint URL for Prod stage for the muphone microservice"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

